"""Model adapters used by the public pipeline and baseline scripts.

The module is import-safe in no-model environments. Heavy dependencies such as
torch and transformers are imported only when a local model adapter is created.
"""

from __future__ import annotations

import json
import os
import urllib.error
import urllib.request
from dataclasses import dataclass
from typing import Any, Dict, Mapping, Optional


@dataclass
class GenerationResult:
    """Text generated by a planner or completion model."""

    text: str
    token_count: Optional[int] = None
    raw: Optional[Any] = None


class MockTextGenerator:
    """Small deterministic adapter for smoke tests."""

    def __init__(self, label: str = "mock"):
        self.label = label
        self.tokenizer = None

    def generate(self, prompt: str, system: Optional[str] = None, token_bias: Optional[Mapping[int, float]] = None) -> GenerationResult:
        del system, token_bias
        text = "Mock response generated for release smoke testing.\n\n" + str(prompt).strip()[:800]
        return GenerationResult(text=text, token_count=len(text.split()))


class LocalHFGenerator:
    """HuggingFace causal-LM adapter for planner, target, and baselines."""

    def __init__(
        self,
        model_path: str,
        max_new_tokens: int = 2048,
        temperature: float = 0.7,
        top_p: float = 0.95,
        top_k: int = 50,
        device_map: str = "auto",
        torch_dtype: str = "auto",
        trust_remote_code: bool = True,
    ):
        if not model_path:
            raise ValueError("model_path is required for local generation")

        import torch
        from transformers import AutoModelForCausalLM, AutoTokenizer

        self.model_path = model_path
        self.max_new_tokens = int(max_new_tokens)
        self.temperature = float(temperature)
        self.top_p = float(top_p)
        self.top_k = int(top_k)
        self.torch = torch

        dtype = None
        if torch_dtype and torch_dtype != "auto":
            dtype = getattr(torch, str(torch_dtype), None)
            if dtype is None:
                raise ValueError(f"unknown torch dtype: {torch_dtype}")

        model_kwargs: Dict[str, Any] = {
            "trust_remote_code": bool(trust_remote_code),
            "device_map": device_map,
        }
        if dtype is not None:
            model_kwargs["torch_dtype"] = dtype

        self.tokenizer = AutoTokenizer.from_pretrained(
            model_path,
            trust_remote_code=bool(trust_remote_code),
            padding_side="left",
        )
        self.model = AutoModelForCausalLM.from_pretrained(model_path, **model_kwargs)
        if self.tokenizer.pad_token_id is None and self.tokenizer.eos_token_id is not None:
            self.tokenizer.pad_token = self.tokenizer.eos_token
        self.model.eval()

    def _format_prompt(self, prompt: str, system: Optional[str]) -> str:
        system_text = system or "You are a helpful assistant."
        messages = [
            {"role": "system", "content": system_text},
            {"role": "user", "content": str(prompt)},
        ]
        if hasattr(self.tokenizer, "apply_chat_template"):
            try:
                return self.tokenizer.apply_chat_template(
                    messages,
                    tokenize=False,
                    add_generation_prompt=True,
                    enable_thinking=False,
                )
            except TypeError:
                return self.tokenizer.apply_chat_template(
                    messages,
                    tokenize=False,
                    add_generation_prompt=True,
                )
        return f"{system_text}\n\nUser:\n{prompt}\n\nAssistant:\n"

    def _device(self):
        try:
            return next(self.model.parameters()).device
        except StopIteration:  # pragma: no cover - defensive
            return "cpu"

    def _logits_processor(self, token_bias: Optional[Mapping[int, float]]):
        if not token_bias:
            return None
        from transformers import LogitsProcessor, LogitsProcessorList

        class PreferenceBiasProcessor(LogitsProcessor):
            def __init__(self, bias: Mapping[int, float]):
                self.bias = {int(k): float(v) for k, v in bias.items()}

            def __call__(self, input_ids, scores):
                del input_ids
                for token_id, value in self.bias.items():
                    if 0 <= token_id < scores.shape[-1]:
                        scores[:, token_id] = scores[:, token_id] + value
                return scores

        return LogitsProcessorList([PreferenceBiasProcessor(token_bias)])

    def generate(self, prompt: str, system: Optional[str] = None, token_bias: Optional[Mapping[int, float]] = None) -> GenerationResult:
        formatted = self._format_prompt(prompt, system)
        inputs = self.tokenizer([formatted], return_tensors="pt", padding=True).to(self._device())
        kwargs: Dict[str, Any] = {
            "max_new_tokens": self.max_new_tokens,
            "do_sample": self.temperature > 0,
            "temperature": self.temperature if self.temperature > 0 else None,
            "top_p": self.top_p,
            "top_k": self.top_k,
            "pad_token_id": self.tokenizer.eos_token_id,
        }
        logits_processor = self._logits_processor(token_bias)
        if logits_processor is not None:
            kwargs["logits_processor"] = logits_processor
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        with self.torch.no_grad():
            output_ids = self.model.generate(**inputs, **kwargs)
        generated = output_ids[0, inputs.input_ids.shape[1] :]
        text = self.tokenizer.decode(generated, skip_special_tokens=True)
        return GenerationResult(text=text, token_count=int(generated.numel()), raw=None)


class OpenAICompatibleGenerator:
    """OpenAI-compatible chat completion adapter with key-free configuration."""

    def __init__(
        self,
        base_url: str,
        model: str,
        credential_env: str = "PROVIDER_KEY",
        max_new_tokens: int = 2048,
        temperature: float = 0.7,
        timeout_seconds: int = 120,
    ):
        if not base_url:
            raise ValueError("base_url is required for API generation")
        if not model:
            raise ValueError("model is required for API generation")
        self.base_url = base_url.rstrip("/")
        self.model = model
        self.credential_env = credential_env
        self.max_new_tokens = int(max_new_tokens)
        self.temperature = float(temperature)
        self.timeout_seconds = int(timeout_seconds)
        self.tokenizer = None

    def _endpoint(self) -> str:
        if self.base_url.endswith("/chat/completions"):
            return self.base_url
        return self.base_url + "/chat/completions"

    def generate(self, prompt: str, system: Optional[str] = None, token_bias: Optional[Mapping[int, float]] = None) -> GenerationResult:
        credential = os.environ.get(self.credential_env)
        if not credential:
            raise RuntimeError(f"missing API credential environment variable: {self.credential_env}")

        payload: Dict[str, Any] = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system or "You are a helpful assistant."},
                {"role": "user", "content": str(prompt)},
            ],
            "temperature": self.temperature,
            "max_tokens": self.max_new_tokens,
        }
        if token_bias:
            payload["logit_bias"] = {str(int(k)): float(v) for k, v in token_bias.items()}

        body = json.dumps(payload).encode("utf-8")
        request = urllib.request.Request(
            self._endpoint(),
            data=body,
            headers={
                "Authorization": f"Bearer {credential}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=self.timeout_seconds) as response:
                raw = json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:  # pragma: no cover - network path
            detail = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"API request failed with status {exc.code}: {detail}") from exc

        choice = (raw.get("choices") or [{}])[0]
        message = choice.get("message") or {}
        text = message.get("content")
        if text is None:
            text = choice.get("text", "")
        usage = raw.get("usage") or {}
        token_count = usage.get("completion_tokens")
        return GenerationResult(text=str(text or ""), token_count=token_count, raw=raw)


def make_text_generator(config: Mapping[str, Any], default_kind: str = "local") -> Any:
    """Create a text generator from a config mapping."""
    kind = str(config.get("kind") or default_kind).lower()
    common = {
        "max_new_tokens": int(config.get("max_new_tokens", 2048)),
        "temperature": float(config.get("temperature", 0.7)),
    }
    if kind == "mock":
        return MockTextGenerator()
    if kind == "local":
        return LocalHFGenerator(
            model_path=str(config.get("model_path") or ""),
            max_new_tokens=common["max_new_tokens"],
            temperature=common["temperature"],
            top_p=float(config.get("top_p", 0.95)),
            top_k=int(config.get("top_k", 50)),
            device_map=str(config.get("device_map", "auto")),
            torch_dtype=str(config.get("torch_dtype", "auto")),
            trust_remote_code=bool(config.get("trust_remote_code", True)),
        )
    if kind in {"api", "openai", "openai_compatible"}:
        return OpenAICompatibleGenerator(
            base_url=str(config.get("base_url") or ""),
            model=str(config.get("model") or ""),
            credential_env=str(config.get("credential_env", "PROVIDER_KEY")),
            max_new_tokens=common["max_new_tokens"],
            temperature=common["temperature"],
            timeout_seconds=int(config.get("timeout_seconds", 120)),
        )
    raise ValueError(f"unknown text generator kind: {kind}")
